# Generated by Django 6.0.1 on 2026-01-30 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_days', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_identifier', models.CharField(help_text='Email o codice identificativo', max_length=255, verbose_name='Identificativo partecipante')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Assente'), ('EXCUSED', 'Giustificato')], default='ABSENT', max_length=20, verbose_name='Stato')),
                ('notes', models.TextField(blank=True, help_text='Es: certificato medico, ritardo, ecc.', verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo aggiornamento')),
                ('course_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='course_days.courseday', verbose_name='Giornata')),
            ],
            options={
                'verbose_name': 'Presenza',
                'verbose_name_plural': 'Presenze',
                'ordering': ['course_day__date', 'participant_identifier'],
            },
        ),
    ]
