# Generated by Django 6.0.1 on 2026-01-30 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Collegato quando il partecipante si registra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('course_day', 'participant_identifier')},
        ),
    ]
