# Generated by Django 6.0.1 on 2026-01-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('description', models.CharField(blank=True, help_text='Es: Lezione 1 - Introduzione a Django', max_length=255, verbose_name='Descrizione')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='Giorno festivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Giornata Corso',
                'verbose_name_plural': 'Giornate Corso',
                'ordering': ['date'],
            },
        ),
    ]
